apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: 
      requests:
        cpu: "6000m"
        memory: "100Gi"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  