apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - command:
    - ping
    - google.com
    image: busybox
    name: busybox
  dnsPolicy: ClusterFirst
  restartPolicy: Always
